- name: Installing Nova and its prerequisites
  apt:
    name:
      - nova-compute
      - python3-openstackclient
    state: present
    update_cache: yes

- name: Restarting/Starting Nova
  service:
     name: nova-compute
     state: restarted
     enabled: yes
